~ _s./* (improved!)
Signed-off-by: Felix C. Stegerman <flx@obfusk.net>

diff --git a/_scripts/bootstrap-deps b/_scripts/bootstrap-deps
--- a/_scripts/bootstrap-deps
+++ b/_scripts/bootstrap-deps
@@ -1,6 +1,8 @@
 #!/bin/bash
 
-[ -d _deps ] || mkdir _deps
+function die () { echo "error: $1" > &2; exit 1; }
+
+[ -d _deps ] || mkdir _deps || die 'failed to mkdir _deps'
 
 while read name url; do
   echo "bootstrapping $name ..."
@@ -10,7 +12,7 @@ while read name url; do
 
     git clone "$url" _deps/"$name"
   else
-    echo 'exists; skipping'
+    echo 'exists; skipping.'
   fi
 done < _depsources
 
diff --git a/_scripts/git-deps b/_scripts/git-deps
--- a/_scripts/git-deps
+++ b/_scripts/git-deps
@@ -1,14 +1,18 @@
 #!/bin/bash
 
-# TODO: list
+function die () { echo "error: $1" > &2; exit 1; }
 
-for name in $( cat _deps/_update ); do
+if [ -n "$GIT_DEPS_DIRS" ]; then
+  ds=( $GIT_DEPS_DIRS )
+else
+  ds=( $( cat _deps/_update ) )
+fi
+
+for name in "${ds[@]}"; do
   echo "==> $name <=="
-
-  pushd _deps/"$name"
+  pushd _deps/"$name" > /dev/null || die "could not pushd _deps/$name"
     git "$@"
-  popd
-
+  popd > /dev/null
   echo
 done
 
diff --git a/_scripts/update-deps b/_scripts/update-deps
--- a/_scripts/update-deps
+++ b/_scripts/update-deps
@@ -1,21 +1,18 @@
 #!/bin/bash
 
-# TODO: remote name, branches
+function die () { echo "error: $1" > &2; exit 1; }
 
-for name in $( cat _deps/_update ); do
+if [ -n "$UPDATE_DEPS_DIRS" ]; then
+  ds=( $UPDATE_DEPS_DIRS )
+else
+  ds=( $( cat _deps/_update ) )
+fi
+
+for name in "${ds[@]}"; do
   echo "updating $name ..."
-
-  pushd _deps/"$name"
-    for branch in $( git branch | sed 's!^..!!' ); do
-      echo "pulling branch $branch ..."
-
-      git checkout "$branch"
-      git pull origin "$branch"
-
-      echo 'done.'
-    done
-  popd
-
+  pushd _deps/"$name" > /dev/null || die "could not pushd _deps/$name"
+    git pull
+  popd > /dev/null
   echo 'done.'
 done
 
