~ _s./* (fix: redirect)
Signed-off-by: Felix C. Stegerman <flx@obfusk.net>

diff --git a/_scripts/git-deps b/_scripts/git-deps
--- a/_scripts/git-deps
+++ b/_scripts/git-deps
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-function die () { echo "error: $1" > &2; exit 1; }
+function die () { echo "error: $1" >&2; exit 1; }
 
 if [ -n "$GIT_DEPS_DIRS" ]; then
   ds=( $GIT_DEPS_DIRS )
diff --git a/_scripts/update-deps b/_scripts/update-deps
--- a/_scripts/update-deps
+++ b/_scripts/update-deps
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-function die () { echo "error: $1" > &2; exit 1; }
+function die () { echo "error: $1" >&2; exit 1; }
 
 if [ -n "$UPDATE_DEPS_DIRS" ]; then
   ds=( $UPDATE_DEPS_DIRS )
